// Generated by envctl from services.yaml
// DO NOT EDIT MANUALLY - Regenerate with: envctl generate pm2 pustikorijen

module.exports = {
  "apps": [
    {
      "name": "pustikorijen-dev-backend",
      "cwd": "/home/bohhem/projects/pustikorijen/backend",
      "script": "npm",
      "args": "run dev",
      "env": {
        "NODE_ENV": "development",
        "PORT": 5001
      },
      "watch": false,
      "instances": 1,
      "autorestart": true,
      "max_restarts": 3,
      "error_file": "/home/bohhem/projects/pustikorijen/logs/pm2/pustikorijen-backend-error.log",
      "out_file": "/home/bohhem/projects/pustikorijen/logs/pm2/pustikorijen-backend-out.log"
    },
    {
      "name": "pustikorijen-dev-frontend",
      "cwd": "/home/bohhem/projects/pustikorijen/frontend",
      "script": "npm",
      "args": "run dev",
      "env": {},
      "watch": false,
      "instances": 1,
      "autorestart": true,
      "max_restarts": 3,
      "error_file": "/home/bohhem/projects/pustikorijen/logs/pm2/pustikorijen-frontend-error.log",
      "out_file": "/home/bohhem/projects/pustikorijen/logs/pm2/pustikorijen-frontend-out.log"
    }
  ]
};
